// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef enum YGOSharp_OCGWrapper_Enums_CardPosition
{
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceUpAttack = 1,
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceDownAttack = 2,
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceUpDefence = 4,
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceDownDefence = 8,
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceUp = 5,
    YGOSharp_OCGWrapper_Enums_CardPosition_FaceDown = 10,
    YGOSharp_OCGWrapper_Enums_CardPosition_Attack = 3,
    YGOSharp_OCGWrapper_Enums_CardPosition_Defence = 12
} YGOSharp_OCGWrapper_Enums_CardPosition;

typedef enum YGOSharp_OCGWrapper_Enums_CardLocation
{
    YGOSharp_OCGWrapper_Enums_CardLocation_Deck = 1,
    YGOSharp_OCGWrapper_Enums_CardLocation_Hand = 2,
    YGOSharp_OCGWrapper_Enums_CardLocation_MonsterZone = 4,
    YGOSharp_OCGWrapper_Enums_CardLocation_SpellZone = 8,
    YGOSharp_OCGWrapper_Enums_CardLocation_Grave = 16,
    YGOSharp_OCGWrapper_Enums_CardLocation_Removed = 32,
    YGOSharp_OCGWrapper_Enums_CardLocation_Extra = 64,
    YGOSharp_OCGWrapper_Enums_CardLocation_Overlay = 128,
    YGOSharp_OCGWrapper_Enums_CardLocation_Onfield = 12,
    YGOSharp_OCGWrapper_Enums_CardLocation_FieldZone = 256,
    YGOSharp_OCGWrapper_Enums_CardLocation_PendulumZone = 512
} YGOSharp_OCGWrapper_Enums_CardLocation;

typedef enum WindBot_Game_AI_ExecutorType
{
    WindBot_Game_AI_ExecutorType_Summon = 0,
    WindBot_Game_AI_ExecutorType_SpSummon = 1,
    WindBot_Game_AI_ExecutorType_Repos = 2,
    WindBot_Game_AI_ExecutorType_MonsterSet = 3,
    WindBot_Game_AI_ExecutorType_SpellSet = 4,
    WindBot_Game_AI_ExecutorType_Activate = 5,
    WindBot_Game_AI_ExecutorType_SummonOrSet = 6,
    WindBot_Game_AI_ExecutorType_GoToBattlePhase = 7,
    WindBot_Game_AI_ExecutorType_GoToMainPhase2 = 8,
    WindBot_Game_AI_ExecutorType_GoToEndPhase = 9
} WindBot_Game_AI_ExecutorType;

typedef MonoEmbedObject WindBot_Game_AI_DefaultExecutor;
typedef MonoEmbedObject WindBot_Game_AI_Executor;

MONO_EMBEDDINATOR_API bool WindBot_Game_AI_DefaultExecutor_OnSelectBattleReplay(WindBot_Game_AI_DefaultExecutor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_DefaultExecutor_OnNewTurn(WindBot_Game_AI_DefaultExecutor* object);

MONO_EMBEDDINATOR_API int32_t WindBot_Game_AI_Executor_OnRockPaperScissors(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API bool WindBot_Game_AI_Executor_OnSelectHand(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_OnChainEnd(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_OnNewPhase(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_OnNewTurn(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_OnDraw(WindBot_Game_AI_Executor* object, int32_t player);
MONO_EMBEDDINATOR_API bool WindBot_Game_AI_Executor_OnSelectYesNo(WindBot_Game_AI_Executor* object, int64_t desc);
MONO_EMBEDDINATOR_API int32_t WindBot_Game_AI_Executor_OnSelectPlace(WindBot_Game_AI_Executor* object, int64_t cardId, int32_t player, YGOSharp_OCGWrapper_Enums_CardLocation location, int32_t available);
MONO_EMBEDDINATOR_API bool WindBot_Game_AI_Executor_OnSelectBattleReplay(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_AddExecutor(WindBot_Game_AI_Executor* object, WindBot_Game_AI_ExecutorType type, int32_t cardId);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_AddExecutor_1(WindBot_Game_AI_Executor* object, WindBot_Game_AI_ExecutorType type);
MONO_EMBEDDINATOR_API const char* WindBot_Game_AI_Executor_get_Deck(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_set_Deck(WindBot_Game_AI_Executor* object, const char* value);
MONO_EMBEDDINATOR_API WindBot_Game_AI_ExecutorType WindBot_Game_AI_Executor_get_Type(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_set_Type(WindBot_Game_AI_Executor* object, WindBot_Game_AI_ExecutorType value);
MONO_EMBEDDINATOR_API int64_t WindBot_Game_AI_Executor_get_ActivateDescription(WindBot_Game_AI_Executor* object);
MONO_EMBEDDINATOR_API void WindBot_Game_AI_Executor_set_ActivateDescription(WindBot_Game_AI_Executor* object, int64_t value);

MONO_EMBEDDINATOR_END_DECLS
